# Generated by Django 3.1.4 on 2021-01-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='map',
            field=models.CharField(default='', max_length=50),
        ),
    ]
