# Generated by Django 3.1.4 on 2021-01-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0002_person_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(default='', max_length=50),
        ),
    ]
