# Generated by Django 3.1.4 on 2021-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0003_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alive',
            field=models.BooleanField(default='True'),
        ),
    ]
