# Generated by Django 3.1.4 on 2021-01-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0004_person_alive'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
    ]
