# Generated by Django 3.1.4 on 2021-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NPC', '0005_person_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='icon',
            field=models.ImageField(blank=True, default='images/placeholder.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
